language: java
jdk:
  - oraclejdk8
  - openjdk8
script: "mvn clean install -P checks"

notifications:
  email: # only send an email if build fails
    on_success: never
    on_failure: always
